name: Notes Application CI Pipeline
on: 
  - push:
      branches:
        - main
        - dev
  - pull_request:
      branches:
        - main
        - dev

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run linter
        run: yarn lint
